version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - /Users/jinam/_javascript_toyprojects/ping_v0.1/nginx.conf:/etc/nginx/nginx.conf:ro
      - /Users/jinam/_javascript_toyprojects/ping_v0.1/frontend:/var/www/html
    restart: on-failure
    ports:
      - 3000:3000
