version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - /goinfre/jinam/_javascript_toyprojects/shopping-cart-with-vanillaJS/nginx.conf:/etc/nginx/nginx.conf:ro
      - /goinfre/jinam/_javascript_toyprojects/shopping-cart-with-vanillaJS/starter/frontend:/var/www/html
    restart: on-failure
    ports:
      - 3000:3000
